[Directory]
# absolute path to where this project is cloned or downloaded
path='C:\Users\nhill_mliw72r\Documents\Code_Projects> '
# ----------------------------------------------------------
[Background]
# absolute path to the background video e.g: Desktop/minecraft.mp4
path='C:\Users\nhill_mliw72r\Documents\Code_Projects\Minecraft.mp4'

# ----------------------------------------------------------
[RedditCredential]
client_id='5eSatr1X4a9klH0fGwKVzg'
client_secret='ovtxzoc4T4LiYSTsIDOaJvVNyDZhgQ'
user_agent='SRD Scraping'
username='Glittering_Let1087'
passkey='Jmnza@04'
# ----------------------------------------------------------
[YoutubeCredential]
client_id=''
client_secret=''
# ----------------------------------------------------------
[Reddit]
# the subredit for which reddit posts are taken
subreddit='AskReddit'
# number of top comments
topn_comments=7
# ----------------------------------------------------------
[VideoSetup]
# the total duration of the final video in seconds
total_video_duration=60
# pause between reading the next comment (in seconds)
pause=0.7
# ----------------------------------------------------------
[App]
# whether the result video should be uploaded to your youtube channel
upload_to_youtube=false
# how often should the app be run (in seconds) e.g: every 6 hours -> 21600 seconds
run_every=21600
